name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]           # ← if you’ve bumped to Node 20; otherwise keep 18.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Auto-format
        run: yarn format        # ← runs `prettier --write`

      - name: Check formatting
        run: yarn format:check  # ← runs `prettier --check`

      - name: Type-check
        run: yarn tsc --noEmit

      - name: Run tests
        run: yarn test
