name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies (offline)
        run: yarn install --frozen-lockfile --offline

      - name: Lint
        run: yarn lint

      - name: Check formatting
        run: yarn format:check

      - name: Type-check
        run: yarn tsc --noEmit

      - name: Run tests
        run: yarn test
