name: Mobile Build

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  mobile-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # ⬇️  cache step goes right here
      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn          # Yarn’s global cache
            **/node_modules        # project-level installs
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # dependency installation runs after the cache is restored
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: EAS Build
        run: yarn eas build --platform all --non-interactive

      - name: Submit to stores
        run: yarn eas submit -p all --latest
        env:
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PW }}
          EXPO_GOOGLE_SERVICE_ACCOUNT:      ${{ secrets.PLAY_JSON }}
