name: Mobile Build

on:
  push:
    branches:
      - 'release/**'        # glob pattern must use two * for sub-folders
  workflow_dispatch:

jobs:
  mobile-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Configure EAS Project
        if: env.EXPO_PROJECT_ID == ''
        run: eas init --id ${{ secrets.EXPO_PROJECT_ID }} --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Build iOS + Android
      - name: EAS Build
        run: eas build --platform all --non-interactive --profile production
        env:
          EXPO_PROJECT_ID: ${{ secrets.EXPO_PROJECT_ID }}

      # Submit to both stores
      - name: EAS Submit
        run: eas submit -p all --latest
        env:
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PW }}
          EXPO_GOOGLE_SERVICE_ACCOUNT:      ${{ secrets.PLAY_JSON }}
